Use OpSIBLING macro
The Perl core, since 586d4abb8, has had a build mode called
PERL_OP_PARENT, which causes the last sibling in a sibling chain to use
op_sibling to point to the parent, rather than being null. Under this
build mode, op_sibling is now called op_sibparent. This causes errors
of the type:

error: ‘OP {aka const struct op}’ has no member named ‘op_sibling’; did
you mean ‘op_sibparent’?

The name of the field was changed to force programs using op_sibling to
revisit their code in light of this change - now, the last sibling in
a chain will have a non-NULL op_sibparent, and the caller must use
op_moresib to know whether the pointer is to another sibling or to
the parent.

This breakage is now visible in bleadperl, since PERL_OP_PARENT was
made default, and will be default in 5.26.0.

op.h provides a macro, OpSIBLING(o), which behaves correctly, checking
op->moresib under PERL_OP_PARENT, and returning either op_sibparent or
NULL. This patch replaces op_sibling with use that macro.